name: iptv
description: IPTV App
version: 4.2.7+262
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.3

dependencies:
  better_player:
    git:
      url: https://github.com/matthewrice345/betterplayer.git
      ref: Issue1057
  bloc: ^8.1.0
  bloc_concurrency: ^0.2.0
  cached_network_image: ^3.2.2
  carousel_slider: ^4.1.1
  chopper: ^5.0.0
  collection: ^1.16.0
  connectivity_plus: ^3.0.2
  container_tab_indicator: ^0.3.0
  crypto: ^3.0.2
  device_apps: ^2.2.0
  device_info_plus: ^3.2.4
  dio: ^4.0.6
  dropdown_button2: ^1.8.9
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_fadein: ^2.0.0
  flutter_install_apk_silently:
    git:
      url: https://github.com/mis-kcn/flutter_install_apk_silently
  flutter_localizations:
    sdk: flutter
  flutter_localized_locales: ^2.0.3
  flutter_smart_dialog: ^4.5.5+6
  flutter_vlc_player:
    git:
      url: https://github.com/KurtMIS/mdu1_vlc_player
      ref: main
  freezed_annotation: ^2.1.0
  get_it: ^7.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^0.13.5
  hydrated_bloc: ^8.1.0
  intl: ^0.17.0
  json_annotation: ^4.7.0
  loading_animation_widget: ^1.2.0+3
  logging: ^1.1.0
  mdu1_player:
    git:
      url: https://github.com/mis-kcn/mdu1_player
  modal_bottom_sheet: ^2.1.2
  mqtt_client: ^9.7.2
  network_info_plus: ^3.0.1
  package_info_plus: ^1.4.2
  path_provider: ^2.0.11
  percent_indicator: ^4.2.2
  perfect_volume_control: ^1.0.5
  qr_flutter: ^4.0.0
  restart_app: ^1.1.0+1
  rxdart: ^0.27.5
  screen_state: ^2.0.0
  scroll_to_index: ^3.0.1
  scrollable_positioned_list: ^0.3.5
  sentry_flutter: ^6.11.2
  sentry_logging: ^6.13.1
  slide_digital_clock: ^1.0.2
  squadron: ^4.3.1
  timer_builder: ^2.0.0
  url_launcher: ^6.1.6
  version: ^3.0.2
  wifi_info_plugin_plus:
    git:
      url: https://github.com/brasizza/flutter_wifi_info_plugin.git
      ref: master

dev_dependencies:
  build_runner: ^2.2.1
  chopper_generator: ^5.0.0+1
  freezed: ^2.1.0+1
  json_serializable: ^6.4.1

  squadron_builder: ^0.9.0
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - cert.pem
    - assets/
    - assets/menu/
